// <auto-generated />
using System;
using MainSite.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainSite.Database.Migrations
{
    [DbContext(typeof(GamersCommunityDbContext))]
    [Migration("20260905101500_AuthZ")]
    partial class AuthZ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MainSite.Database.Models.Banned", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdModo")
                        .HasColumnType("int");

                    b.Property<int>("IdUserBan")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdModo");

                    b.HasIndex("IdUserBan");

                    b.ToTable("Banned", (string)null);
                });

            modelBuilder.Entity("MainSite.Database.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCountry")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PostalCode")
                        .HasColumnType("numeric(10, 0)");

                    b.HasKey("Id")
                        .HasName("PK_City");

                    b.HasIndex("IdCountry");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("MainSite.Database.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Country");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MainSite.Database.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Link")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NumAddress")
                        .HasColumnType("int");

                    b.Property<string>("PlaceName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Places")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCity");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MainSite.Database.Models.EventsUsersInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdEvent")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdEvent");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdUser");

                    b.ToTable("EventsUsersInterest", (string)null);
                });

            modelBuilder.Entity("MainSite.Database.Models.EventsUsersStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Id");

                    b.ToTable("EventsUsersStatus", (string)null);
                });

            modelBuilder.Entity("MainSite.Database.Models.Friend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdFriendAsking")
                        .HasColumnType("int");

                    b.Property<int>("IdFriendReceive")
                        .HasColumnType("int");

                    b.Property<int>("IdFriendStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdFriendAsking");

                    b.HasIndex("IdFriendReceive");

                    b.HasIndex("IdFriendStatus");

                    b.ToTable("Friend", (string)null);
                });

            modelBuilder.Entity("MainSite.Database.Models.FriendStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("FriendStatus", (string)null);
                });

            modelBuilder.Entity("MainSite.Database.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdType");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("MainSite.Database.Models.GameRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdGame")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGame", "Code")
                        .IsUnique();

                    b.ToTable("GameRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.GameType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_GameType");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("MainSite.Database.Models.GroupRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GroupRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdReceiver")
                        .HasColumnType("int");

                    b.Property<int>("IdSender")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Message");

                    b.HasIndex("IdReceiver");

                    b.HasIndex("IdSender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MainSite.Database.Models.Rank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Rank");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("MainSite.Database.Models.RankRight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdRank")
                        .HasColumnType("int");

                    b.Property<int>("IdRight")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.HasIndex("IdRank");

                    b.HasIndex("IdRight");

                    b.ToTable("RankRights");
                });

            modelBuilder.Entity("MainSite.Database.Models.Right", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Entitled")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK_Right");

                    b.ToTable("Rights");
                });

            modelBuilder.Entity("MainSite.Database.Models.SiteRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SiteRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<Guid>("IdKeycloak")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("datetime");

                    b.Property<string>("Mail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ModificationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Uusers");

                    b.HasIndex(new[] { "Mail" }, "IX_Users")
                        .IsUnique()
                        .HasFilter("[Mail] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserGameRole", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdGameRole")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdGameRole");

                    b.HasIndex("IdGameRole");

                    b.ToTable("UserGameRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserGroupRole", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdGroup")
                        .HasColumnType("int");

                    b.Property<int>("IdGroupRole")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdGroup");

                    b.HasIndex("IdGroupRole");

                    b.ToTable("UserGroupRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserSiteRole", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("IdSiteRole")
                        .HasColumnType("int");

                    b.HasKey("IdUser", "IdSiteRole");

                    b.HasIndex("IdSiteRole");

                    b.ToTable("UserSiteRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.Banned", b =>
                {
                    b.HasOne("MainSite.Database.Models.User", "IdModoNavigation")
                        .WithMany("BannedIdModoNavigations")
                        .HasForeignKey("IdModo")
                        .IsRequired()
                        .HasConstraintName("FK_Banned_Modo");

                    b.HasOne("MainSite.Database.Models.User", "IdUserBanNavigation")
                        .WithMany("BannedIdUserBanNavigations")
                        .HasForeignKey("IdUserBan")
                        .IsRequired()
                        .HasConstraintName("FK_Banned_Users");

                    b.Navigation("IdModoNavigation");

                    b.Navigation("IdUserBanNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.City", b =>
                {
                    b.HasOne("MainSite.Database.Models.Country", "IdCountryNavigation")
                        .WithMany("Cities")
                        .HasForeignKey("IdCountry")
                        .IsRequired()
                        .HasConstraintName("FK_City_Countries");

                    b.Navigation("IdCountryNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.Event", b =>
                {
                    b.HasOne("MainSite.Database.Models.City", "IdCityNavigation")
                        .WithMany("Events")
                        .HasForeignKey("IdCity")
                        .IsRequired()
                        .HasConstraintName("FK_Events_City");

                    b.Navigation("IdCityNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.EventsUsersInterest", b =>
                {
                    b.HasOne("MainSite.Database.Models.Event", "IdEventNavigation")
                        .WithMany("EventsUsersInterests")
                        .HasForeignKey("IdEvent")
                        .IsRequired()
                        .HasConstraintName("FK_EventsUsersInterest_Events");

                    b.HasOne("MainSite.Database.Models.EventsUsersStatus", "IdStatusNavigation")
                        .WithMany("EventsUsersInterests")
                        .HasForeignKey("IdStatus")
                        .IsRequired()
                        .HasConstraintName("FK_EventsUsersInterest_EventsTypeStatusUser");

                    b.HasOne("MainSite.Database.Models.User", "IdUserNavigation")
                        .WithMany("EventsUsersInterests")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_EventsUsersInterest_Users");

                    b.Navigation("IdEventNavigation");

                    b.Navigation("IdStatusNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.Friend", b =>
                {
                    b.HasOne("MainSite.Database.Models.User", "IdFriendAskingNavigation")
                        .WithMany("FriendIdFriendAskingNavigations")
                        .HasForeignKey("IdFriendAsking")
                        .IsRequired()
                        .HasConstraintName("FK_Friend_UsersAsking");

                    b.HasOne("MainSite.Database.Models.User", "IdFriendReceiveNavigation")
                        .WithMany("FriendIdFriendReceiveNavigations")
                        .HasForeignKey("IdFriendReceive")
                        .IsRequired()
                        .HasConstraintName("FK_Friend_UsersReceive");

                    b.HasOne("MainSite.Database.Models.FriendStatus", "IdFriendStatusNavigation")
                        .WithMany("Friends")
                        .HasForeignKey("IdFriendStatus")
                        .IsRequired()
                        .HasConstraintName("FK_Friend_FriendRequestStatus");

                    b.Navigation("IdFriendAskingNavigation");

                    b.Navigation("IdFriendReceiveNavigation");

                    b.Navigation("IdFriendStatusNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.Game", b =>
                {
                    b.HasOne("MainSite.Database.Models.GameType", "IdTypeNavigation")
                        .WithMany("Games")
                        .HasForeignKey("IdType")
                        .IsRequired()
                        .HasConstraintName("FK_Games_GameType");

                    b.Navigation("IdTypeNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.GameRole", b =>
                {
                    b.HasOne("MainSite.Database.Models.Game", "IdGameNavigation")
                        .WithMany()
                        .HasForeignKey("IdGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGameNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.Message", b =>
                {
                    b.HasOne("MainSite.Database.Models.User", "IdReceiverNavigation")
                        .WithMany("MessageIdReceiverNavigations")
                        .HasForeignKey("IdReceiver")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Receiver");

                    b.HasOne("MainSite.Database.Models.User", "IdSenderNavigation")
                        .WithMany("MessageIdSenderNavigations")
                        .HasForeignKey("IdSender")
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Sender");

                    b.Navigation("IdReceiverNavigation");

                    b.Navigation("IdSenderNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.RankRight", b =>
                {
                    b.HasOne("MainSite.Database.Models.Rank", "IdRankNavigation")
                        .WithMany("RankRights")
                        .HasForeignKey("IdRank")
                        .IsRequired()
                        .HasConstraintName("FK_RankRights_Ranks");

                    b.HasOne("MainSite.Database.Models.Right", "IdRightNavigation")
                        .WithMany("RankRights")
                        .HasForeignKey("IdRight")
                        .IsRequired()
                        .HasConstraintName("FK_RankRights_Rights");

                    b.Navigation("IdRankNavigation");

                    b.Navigation("IdRightNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserGameRole", b =>
                {
                    b.HasOne("MainSite.Database.Models.GameRole", "IdGameRoleNavigation")
                        .WithMany("UserGameRoles")
                        .HasForeignKey("IdGameRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainSite.Database.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGameRoleNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserGroupRole", b =>
                {
                    b.HasOne("MainSite.Database.Models.GroupRole", "IdGroupRoleNavigation")
                        .WithMany("UserGroupRoles")
                        .HasForeignKey("IdGroupRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainSite.Database.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdGroupRoleNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.UserSiteRole", b =>
                {
                    b.HasOne("MainSite.Database.Models.SiteRole", "IdSiteRoleNavigation")
                        .WithMany("UserSiteRoles")
                        .HasForeignKey("IdSiteRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MainSite.Database.Models.User", "IdUserNavigation")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdSiteRoleNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("MainSite.Database.Models.City", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MainSite.Database.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("MainSite.Database.Models.Event", b =>
                {
                    b.Navigation("EventsUsersInterests");
                });

            modelBuilder.Entity("MainSite.Database.Models.EventsUsersStatus", b =>
                {
                    b.Navigation("EventsUsersInterests");
                });

            modelBuilder.Entity("MainSite.Database.Models.FriendStatus", b =>
                {
                    b.Navigation("Friends");
                });

            modelBuilder.Entity("MainSite.Database.Models.GameRole", b =>
                {
                    b.Navigation("UserGameRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("MainSite.Database.Models.GroupRole", b =>
                {
                    b.Navigation("UserGroupRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.Rank", b =>
                {
                    b.Navigation("RankRights");
                });

            modelBuilder.Entity("MainSite.Database.Models.Right", b =>
                {
                    b.Navigation("RankRights");
                });

            modelBuilder.Entity("MainSite.Database.Models.SiteRole", b =>
                {
                    b.Navigation("UserSiteRoles");
                });

            modelBuilder.Entity("MainSite.Database.Models.User", b =>
                {
                    b.Navigation("BannedIdModoNavigations");

                    b.Navigation("BannedIdUserBanNavigations");

                    b.Navigation("EventsUsersInterests");

                    b.Navigation("FriendIdFriendAskingNavigations");

                    b.Navigation("FriendIdFriendReceiveNavigations");

                    b.Navigation("MessageIdReceiverNavigations");

                    b.Navigation("MessageIdSenderNavigations");
                });
#pragma warning restore 612, 618
        }
    }
}
